# -*- coding: utf-8 -*-
"""ovarian_cancer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XPVJ6DzWvsozNKVFwTGh5T5caLgoRpop
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score, classification_report

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC

from google.colab import files
uploaded = files.upload()

df = pd.read_csv("ovarian_dataset_50000.csv")

df.head()

df.info()

df.columns = df.columns.str.strip().str.lower()

df.fillna(0, inplace=True)

binary_cols = ['pelvic_pain', 'stomach_swelling', 'persistent_bloating', 'feeling_full_quickly', 'urinary_urgency', 'unexpected_weight_loss', 'abnormal_vaginal_bleeding', 'fatigue', 'back_pain', 'family_history', 'menopause']

for col in binary_cols:

    # If already numeric (0/1), skip
    if df[col].dropna().isin([0, 1]).all():
        continue

    # Otherwise clean and convert
    df[col] = df[col].astype(str).str.strip().str.lower()

    df[col] = df[col].apply(lambda x: 1 if x in ['yes', 'y', 'true', '1'] else
                                      0 if x in ['no', 'n', 'false', '0'] else np.nan)

df[binary_cols] = df[binary_cols].fillna(0)

df.head()

# Encode 'menstrual_history' before splitting
df_encoded = pd.get_dummies(df, columns=['menstrual_history'], drop_first=True)

df_encoded['ca_125_risk'] = (df_encoded['ca_125'] > 35).astype(int)

y = df_encoded['ca_125_risk']
X = df_encoded.drop(['ca_125', 'ca_125_risk'], axis=1)

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)



df['risk_score'] = (
    df['pelvic_pain'] +
    df['fatigue']
)

df['risk'] = df['risk_score'].apply(lambda x: 1 if x >= 1 else 0)

models = {
    "Logistic Regression": LogisticRegression(max_iter=1000),
    "Random Forest": RandomForestClassifier(),
    "SVM": SVC()
}

results = {}

for name, model in models.items():
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    acc = accuracy_score(y_test, y_pred)
    results[name] = acc
    print(f"\n{name} Accuracy:", acc)

param_grid = {
    'n_estimators': [50, 100],
    'max_depth': [None, 10, 20]
}

grid = GridSearchCV(RandomForestClassifier(), param_grid, cv=3)
grid.fit(X_train, y_train)

best_model = grid.best_estimator_

y_pred_best = best_model.predict(X_test)

print("\nBest Model Accuracy:", accuracy_score(y_test, y_pred_best))
print("\nClassification Report:\n", classification_report(y_test, y_pred_best))

plt.figure()
plt.bar(results.keys(), results.values())
plt.title("Model Accuracy Comparison")
plt.xticks(rotation=30)
plt.ylabel("Accuracy")
plt.show()

risk_counts = df['risk'].value_counts()

plt.figure()
risk_counts.plot(kind='bar')
plt.title("Risk Level Distribution")
plt.xlabel("Risk (0 = Low, 1 = High)")
plt.ylabel("Count")
plt.show()

importances = best_model.feature_importances_
features = X.columns

plt.figure()
plt.bar(features, importances)
plt.title("Feature Importance")
plt.xticks(rotation=45)
plt.show()